name: CI-PORTAL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Nodejs
      - name: nodejs Install
        run:  sudo apt-get install nodejs -y
      - name: node version
        run: nodejs -v
      - name: npm install
        run: sudo apt-get  install npm  -y
      - name: npm version
        run: npm -v
